export const metadata = {
  title: "Privacy Policy",
};

const PrivacyPolicy = () => {
  return (
    <main className='max-w-4xl mx-auto pt-40 py-24 px-6'>
      <h1 className='text-4xl font-bold mb-8'>Privacy Policy</h1>
      <p className='text-gray-600 mb-4'>Last updated: October 07, 2024</p>
      <p className='text-gray-700 mb-6'>
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className='text-gray-700 mb-6'>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2 className='text-3xl font-semibold mt-12 mb-6'>
        Interpretation and Definitions
      </h2>
      <h3 className='text-2xl font-medium mt-6 mb-4'>Interpretation</h3>
      <p className='text-gray-700 mb-6'>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className='text-2xl font-medium mt-6 mb-4'>Definitions</h3>
      <ul className='list-disc list-inside space-y-4'>
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by, or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares,
          equity interest, or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the
          Company&quot;, &quot;We&quot;, &quot;Us&quot;, or &quot;Our&quot; in
          this Agreement) refers to Moroz Financial Group PLLC, 770 W Dundee Rd.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device, or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Illinois, United States
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone, or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to Moroz Financial Group, accessible
          from
          <a
            href='https://moroz-financial-group.vercel.app/'
            target='_blank'
            rel='noreferrer'
            className='text-blue-600 underline'
          >
            https://moroz-financial-group.vercel.app/
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className='text-3xl font-semibold mt-12 mb-6'>
        Collecting and Using Your Personal Data
      </h2>
      <h3 className='text-2xl font-medium mt-6 mb-4'>
        Types of Data Collected
      </h3>
      <h4 className='text-xl font-medium mt-4 mb-2'>Personal Data</h4>
      <p className='text-gray-700 mb-6'>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className='list-disc list-inside space-y-2'>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <h4 className='text-xl font-medium mt-8 mb-4'>Usage Data</h4>
      <p className='text-gray-700 mb-6'>
        Usage Data is collected automatically when using the Service.
        <br />
        Usage Data may include information such as Your Device&#39;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers, and other
        diagnostic data.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Tracking Technologies and Cookies
      </h3>
      <p className='text-gray-700 mb-6'>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Use of Your Personal Data
      </h3>
      <p className='text-gray-700 mb-6'>
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className='list-disc list-inside space-y-2'>
        <li>To provide and maintain our Service.</li>
        <li>To manage Your Account.</li>
        <li>For business transfers and legal requirements.</li>
        <li>To contact You.</li>
        <li>To manage Your requests.</li>
        <li>For other purposes like data analysis and improvement.</li>
      </ul>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Retention of Your Personal Data
      </h3>
      <p className='text-gray-700 mb-6'>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Transfer of Your Personal Data
      </h3>
      <p className='text-gray-700 mb-6'>
        Your information, including Personal Data, may be transferred to — and
        maintained on — computers located outside of Your state, province,
        country, or other governmental jurisdiction.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Delete Your Personal Data
      </h3>
      <p className='text-gray-700 mb-6'>
        You have the right to delete your Personal Data.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Disclosure of Your Personal Data
      </h3>
      <p className='text-gray-700 mb-6'>
        We may disclose your Personal Data for legal reasons or business
        purposes.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>Children&#39;s Privacy</h3>
      <p className='text-gray-700 mb-6'>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>
        Changes to this Privacy Policy
      </h3>
      <p className='text-gray-700 mb-6'>
        We may update Our Privacy Policy from time to time. You are advised to
        review this Privacy Policy periodically for any changes.
      </p>

      <h3 className='text-2xl font-medium mt-8 mb-4'>Contact Us</h3>
      <p className='text-gray-700'>
        If you have any questions about this Privacy Policy, You can contact us:
        <br />
        By email:{" "}
        <a
          href='mailto:info@morozfinancial.com'
          className='text-blue-600 underline'
        >
          info@morozfinancial.com
        </a>
      </p>
    </main>
  );
};

export default PrivacyPolicy;
